#!/bin/bash
# This script will run LDA for a series of topic numbers.
#
# Input lines should be of the following format
#  modelName MODELNAME numTopics optimizationInterval
# 1. modelName is a short name for the model that also specifies the
# directory on hdfs that will house the factor matrices.
# 2. MODELNAME is an upper case name that is used in the transpose file names.
# 3. numTopics specifies the number of reduced dimensions (topics)
# 4. optimizationInterval specifies the train interval at which hyper parameters
# should be adjusted, set to 0 if it should be off.

# Change this to store the matrices in a different base directory
BASE=/home/stevens35

# Remove "s from the environment variable to work around a stupid bug in hadoop.
export HADOOP_CLIENT_OPTS=`echo $HADOOP_CLIENT_OPTS | tr -d '"'`

# A helper method to determine the local size of a file.
function localSize() {
   ls -l $1 | awk '{ print $5 }'
}

# A helper method to determine the size of a file on hdfs.
function hdfsSize() {
   s=`hadoop dfs -ls $1 | awk '{ print $5 }'`
   echo ${s:1}
}

# A helper method to copy files from hdfs to local disk.
function copyToLocal() {
    hadoop dfs -copyToLocal $2/$1 $1
    while [ ! -f $1 ]; do sleep 1; done
}

# A helper method to copy files from local disk to hdfs.
function copyFromLocal() {
    hadoop dfs -rm $2/$1
    hadoop dfs -copyFromLocal $1 $2/$1
    while [ "`localSize $1`" != "`hdfsSize $2/$1`" ]; do sleep 1; done
}

while read input
do
    model=`echo $input | cut -d " " -f 1`
    MODEL=`echo $input | cut -d " " -f 2`
    numTopics=`echo $input | cut -d " " -f 3`
    optInterval=`echo $input | cut -d " " -f 4`
    fraction=`echo $input | cut -d " " -f 5`
    skip=`echo $input | cut -d " " -f 6`

    outBase=nyt03-${fraction}_${MODEL}_$numTopics
    scala -J-Xmx4g -cp mallet.jar:trove.jar:sspace-lib.jar RunLDA.scala \
        docs.txt $outBase $numTopics $optInterval $skip
    copyFromLocal $outBase-ws.dat $BASE/${model}_topic/
    copyFromLocal $outBase-ws.dat.top10 $BASE/${model}_topic/
    copyFromLocal $outBase-ds.dat.transpose $BASE/${model}_topic/
done >&2
