#!/bin/bash
# This script will reduce a given matrix using the S-Space Package.  
# It determines the reduction model and the number of reduced dimensions
# (topics), based on line based input.  
#
# Input lines should be of the following format
#  modelName MODELNAME numTopics
# 1. modelName is a short name for the model that also specifies the
# directory on hdfs that will house the factor matrices.  
# 2. MODELNAME is an upper case name that ReductionEval accepts as a valid
# model.  
# 3. numTopics specifies the number of reduced dimensions (topics)
#
# For example, 
# svd SVD 100
# will run SVD on the input matrix for 100 dimensions, and store the two factor
# matrices in $BASE/svd_topic

# Change this to store the matrices in a different base directory
BASE=/home/stevens35

# Remove "s from the environment variable to work around a stupid bug in hadoop.
# Don't remove this.
export HADOOP_CLIENT_OPTS=`echo $HADOOP_CLIENT_OPTS | tr -d '"'`

# A helper method to determine the local size of a file.
function localSize() {
   ls -l $1 | awk '{ print $5 }'
}

# A helper method to determine the size of a file on hdfs.
function hdfsSize() {
   s=`hadoop dfs -ls $1 | awk '{ print $5 }'`
   echo ${s:1}
}

# A helper method to copy files from hdfs to local disk.
function copyToLocal() {
    hadoop dfs -copyToLocal $2/$1 $1
    while [ ! -f $1 ]; do sleep 1; done
}

# A helper method to copy files from local disk to hdfs.
function copyFromLocal() {
    [ -f $1 ] || return
    hadoop dfs -rm $2/$1
    hadoop dfs -copyFromLocal $1 $2/$1
    while [ "`localSize $1`" != "`hdfsSize $2/$1`" ]; do sleep 1; done
}

while read line
do
    model=`echo $line | cut -d " " -f 1`
    MODEL=`echo $line | cut -d " " -f 2`
    numTopics=`echo $line | cut -d " " -f 3`
    fraction=`echo $line | cut -d " " -f 4`
    skip=`echo $line | cut -d " " -f 5`

    echo running $line
    ws=nyt03-${fraction}_${MODEL}_$numTopics-ws.dat
    ds=nyt03-${fraction}_${MODEL}_$numTopics-ds.dat
    tsp=$ds.transpose
    java -cp sspace-lib.jar:trove.jar edu.ucla.sspace.tools.ReductionEval \
         -f $skip -r $numTopics -a $MODEL -w $ws -d $ds termDocMatrix.mat
    java -Xmx2g -cp sspace-lib.jar edu.ucla.sspace.tools.SelectTopKWords \
         termDocMatrix.basis $ws > $ws.top10
    java -Xmx2g -cp sspace-lib.jar edu.ucla.sspace.tools.MatrixTranspose \
         DENSE_TEXT $ds $tsp

    copyFromLocal $ws $BASE/${model}_topic
    copyFromLocal $ws.top10 $BASE/${model}_topic
    copyFromLocal $tsp $BASE/${model}_topic
done >&2
