#!/bin/bash
HDFSJAR="/home/stevens35/topic/sspace-lib.jar"
HDFSDOCS="/home/stevens35/topic/nyt03OneLinePerDoc.txt"
HDFSSECTIONS="/home/stevens35/topic/nyt03DocSections.txt"
#HDFSDOCS="/home/stevens35/topic/nyt_2003_log_entropy.dat"
#HDFSDOCS="/home/stevens35/topic/nyt_2003_log_entropy-matlab.dat"

hadoop dfs -rmr /home/stevens35/convert-output
# Do the runs
$HADOOP_HOME/bin/hadoop jar $HADOOP_HOME/contrib/streaming/hadoop-streaming-0.20.2+737.jar \
    -input /home/stevens35/convert-input \
    -output /home/stevens35/convert-output \
    -mapper convertToCSV.sh \
    -reducer NONE \
    -verbose \
    -file convertToCSV.sh \
    -file convertToCSV.py \
    -jobconf mapred.job.name="StreamTest" \
    -jobconf mapred.task.timeout="60000000" \
    -cacheFile hdfs://thormaster:54310$HDFSDOCS#nyt03OneLinePerDoc.txt \
    -cacheFile hdfs://thormaster:54310$HDFSSECTIONS#nyt03DocSections.txt \
    -cacheFile hdfs://thormaster:54310$HDFSJAR#sspace-lib.jar
