#!/bin/bash
HDFSJAR="/home/stevens35/topic/sspace-wordsi.jar"

hadoop dfs -rmr /home/stevens35/consensus-output
# Do the runs
$HADOOP_HOME/bin/hadoop jar $HADOOP_HOME/contrib/streaming/hadoop-streaming-0.20.2+737.jar \
    -input /home/stevens35/consensus-input \
    -output /home/stevens35/consensus-output \
    -mapper consensusCluster.sh \
    -reducer NONE \
    -verbose \
    -file consensusCluster.sh \
    -file ConsensusCluster.scala \
    -jobconf mapred.job.name="ConsensusClustering" \
    -jobconf mapred.task.timeout="60000000" \
    -cacheFile hdfs://thormaster:54310$HDFSJAR#sspace-wordsi.jar
