#!/bin/bash
HDFSTROVE="/home/stevens35/topic/trove.jar"
HDFSMALLET="/home/stevens35/topic/mallet.jar"
HDFSSSpace="/home/stevens35/topic/sspace-lib.jar"
HDFSDOCS="/home/stevens35/topic/nyt03OneLinePerDoc.txt"
HDFSSCALA="/home/stevens35/topic/RunLDA.scala"

hadoop dfs -rmr /home/stevens35/lda-stream-output 

# Do the runs
$HADOOP_HOME/bin/hadoop jar $HADOOP_HOME/contrib/streaming/hadoop-streaming-0.20.2+737.jar \
    -input /home/stevens35/lda-stream-input \
    -output /home/stevens35/lda-stream-output \
    -mapper ldaStream \
    -reducer NONE \
    -verbose \
    -file ldaStream \
    -file RunLDA.scala \
    -jobconf mapred.job.name="BulkLDARuns" \
    -jobconf mapred.task.timeout="60000000" \
    -cacheFile hdfs://thormaster:54310$HDFSMALLET#mallet.jar \
    -cacheFile hdfs://thormaster:54310$HDFSTROVE#trove.jar \
    -cacheFile hdfs://thormaster:54310$HDFSSSpace#sspace-lib.jar \
    -cacheFile hdfs://thormaster:54310$HDFSDOCS#docs.txt 
    #-cacheFile hdfs://thormaster:54310$HDFSSCALA#RunLDA.scala
